/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DODOPoolProxyInterface extends ethers.utils.Interface {
  functions: {
    "addLiquidity(address,uint256,uint256)": FunctionFragment;
    "calculateBaseProportionForSuppliedQuote(address,uint256)": FunctionFragment;
    "calculateLPForReleasingSuppliedQuoteAmount(address,uint256)": FunctionFragment;
    "getQuotePrice(address)": FunctionFragment;
    "removeLiquidity(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateBaseProportionForSuppliedQuote",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateLPForReleasingSuppliedQuoteAmount",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuotePrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateBaseProportionForSuppliedQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateLPForReleasingSuppliedQuoteAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuotePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;

  events: {};
}

export class DODOPoolProxy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DODOPoolProxyInterface;

  functions: {
    addLiquidity(
      poolAddress: string,
      amountTokenBase: BigNumberish,
      amountTokenQuote: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addLiquidity(address,uint256,uint256)"(
      poolAddress: string,
      amountTokenBase: BigNumberish,
      amountTokenQuote: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    calculateBaseProportionForSuppliedQuote(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { baseAmount: BigNumber }>;

    "calculateBaseProportionForSuppliedQuote(address,uint256)"(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { baseAmount: BigNumber }>;

    calculateLPForReleasingSuppliedQuoteAmount(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { baseAmount: BigNumber }>;

    "calculateLPForReleasingSuppliedQuoteAmount(address,uint256)"(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { baseAmount: BigNumber }>;

    getQuotePrice(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { price: BigNumber; decimals: BigNumber }
    >;

    "getQuotePrice(address)"(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { price: BigNumber; decimals: BigNumber }
    >;

    removeLiquidity(
      poolAddress: string,
      lpAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeLiquidity(address,uint256)"(
      poolAddress: string,
      lpAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  addLiquidity(
    poolAddress: string,
    amountTokenBase: BigNumberish,
    amountTokenQuote: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addLiquidity(address,uint256,uint256)"(
    poolAddress: string,
    amountTokenBase: BigNumberish,
    amountTokenQuote: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  calculateBaseProportionForSuppliedQuote(
    poolAddress: string,
    quoteAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "calculateBaseProportionForSuppliedQuote(address,uint256)"(
    poolAddress: string,
    quoteAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateLPForReleasingSuppliedQuoteAmount(
    poolAddress: string,
    quoteAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "calculateLPForReleasingSuppliedQuoteAmount(address,uint256)"(
    poolAddress: string,
    quoteAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getQuotePrice(
    poolAddress: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { price: BigNumber; decimals: BigNumber }
  >;

  "getQuotePrice(address)"(
    poolAddress: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { price: BigNumber; decimals: BigNumber }
  >;

  removeLiquidity(
    poolAddress: string,
    lpAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeLiquidity(address,uint256)"(
    poolAddress: string,
    lpAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    addLiquidity(
      poolAddress: string,
      amountTokenBase: BigNumberish,
      amountTokenQuote: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "addLiquidity(address,uint256,uint256)"(
      poolAddress: string,
      amountTokenBase: BigNumberish,
      amountTokenQuote: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateBaseProportionForSuppliedQuote(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calculateBaseProportionForSuppliedQuote(address,uint256)"(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateLPForReleasingSuppliedQuoteAmount(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calculateLPForReleasingSuppliedQuoteAmount(address,uint256)"(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getQuotePrice(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { price: BigNumber; decimals: BigNumber }
    >;

    "getQuotePrice(address)"(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { price: BigNumber; decimals: BigNumber }
    >;

    removeLiquidity(
      poolAddress: string,
      lpAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { baseAmount: BigNumber; quoteAmount: BigNumber }
    >;

    "removeLiquidity(address,uint256)"(
      poolAddress: string,
      lpAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { baseAmount: BigNumber; quoteAmount: BigNumber }
    >;
  };

  filters: {};

  estimateGas: {
    addLiquidity(
      poolAddress: string,
      amountTokenBase: BigNumberish,
      amountTokenQuote: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addLiquidity(address,uint256,uint256)"(
      poolAddress: string,
      amountTokenBase: BigNumberish,
      amountTokenQuote: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    calculateBaseProportionForSuppliedQuote(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calculateBaseProportionForSuppliedQuote(address,uint256)"(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateLPForReleasingSuppliedQuoteAmount(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calculateLPForReleasingSuppliedQuoteAmount(address,uint256)"(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getQuotePrice(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getQuotePrice(address)"(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeLiquidity(
      poolAddress: string,
      lpAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "removeLiquidity(address,uint256)"(
      poolAddress: string,
      lpAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addLiquidity(
      poolAddress: string,
      amountTokenBase: BigNumberish,
      amountTokenQuote: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addLiquidity(address,uint256,uint256)"(
      poolAddress: string,
      amountTokenBase: BigNumberish,
      amountTokenQuote: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    calculateBaseProportionForSuppliedQuote(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calculateBaseProportionForSuppliedQuote(address,uint256)"(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateLPForReleasingSuppliedQuoteAmount(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calculateLPForReleasingSuppliedQuoteAmount(address,uint256)"(
      poolAddress: string,
      quoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getQuotePrice(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getQuotePrice(address)"(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeLiquidity(
      poolAddress: string,
      lpAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeLiquidity(address,uint256)"(
      poolAddress: string,
      lpAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
